packages:
  - .

allowBuilds:
  cpu-features: false
  esbuild: true
  isolated-vm: false
  sharp: true
  ssh2: false
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@n8n/constants@0.36.1'
  - '@n8n/expression-runtime@0.28.1'
  - '@n8n/tournament@1.10.1'
  - '@n8n/utils@1.45.1'
  - '@n8n/workflow-sdk@0.30.2'
  - n8n-workflow@2.37.2
